import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import { cn } from "@/lib/utils";

const fontText = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gitfix",
  description: "Generated by Upstash",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        fontText.variable,
        "scroll-smooth antialiased bg-zinc-900 text-zinc-50",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
